fixed imports, added authn provider
Flipkart/oauth2_proxy pull request #1
Opened 2018-01-03 12:33 UTC by saisandeep-flipkart

2018-01-12 06:08 UTC, prasanthnarra commented on build/oauth2-proxy/DEBIAN/postinst
> +  makedir "/usr/share/flipkart/$PAC"
This dir is created during Deb installation. Remove this here.

2018-01-12 06:27 UTC, prasanthnarra commented on build/oauth2-proxy/var/lib/flipkart/oauth2-proxy/oauth2-proxy.cfg
> +
These urls should not be exposed in a public github repo

2018-01-12 06:28 UTC, prasanthnarra commented on make-deb.sh
> +ARCH=${2:-$(go env GOARCH)}
internal urls should not be exposed outside

2018-01-12 06:43 UTC, dan13ram commented on README.md
> +* [Google](#google-auth-provider)
Should we be compatible with other auth providers? Since we want everyone to onboard on ONLY authN, I think we should not support other auth providers.

2018-01-12 07:00 UTC, dan13ram commented on build/oauth2-proxy/DEBIAN/postrm
> +if [ "$CMD" == "purge" -o "$CMD" == "remove" ] ; then
extra if checks are not necessary when using -f with rm

2018-01-12 07:12 UTC, dan13ram commented on providers/authn.go
> +func (p *AuthnProvider) getDetails(s *SessionState) {
return error from this function and return the error wherever this function is called

2018-01-12 07:19 UTC, dan13ram commented on providers/authn.go
> +		log.Printf("failed building request %s", err)
use log "github.com/sirupsen/logrus" for levelled logs. 
and set loglevel using one of the following:
log.SetLevel(log.DebugLevel)
log.SetLevel(log.InfoLevel)
log.SetLevel(log.WarnLevel)

2018-01-12 07:21 UTC, dan13ram commented on providers/authn_test.go
> +		&ProviderData{
you can just use &ProviderData{} here

2018-01-12 07:24 UTC, dan13ram commented on providers/authn_test.go
> +func TestAuthnProviderDefaults(t *testing.T) {
change these tests to use table driven tests

2018-01-12 07:37 UTC, dan13ram requested changes
please incorporate changes

2018-01-15 07:26 UTC, dan13ram approved these changes
LGTM

2018-01-19 14:09 UTC, merged